#!/usr/bin/perl -w
# 
# pangram - determine if sentence is a pangram
# Pangrams are sentences constructed by using every letter of the alphabet at least once.

use strict;
use Data::Dumper;

my $sentence = <>;
$sentence =~ s/\s+//g;
my @chars = split(//, $sentence);

my %hash = ();
foreach my $char (@chars) {
    $char =~ tr/A-Z/a-z/;
    $hash{$char}++;
}


my $found = 1;
foreach my $alpha ('a' .. 'z') {
   #print $alpha . "\n";
   if ( !($hash{$alpha}) ) {
       #print "we couldn't find $alpha\n";
       $found = 0;
       last;
   } 
}

if ($found) {
	print "pangram\n";
} else {
    print "not pangram\n";
}
